format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_RH71_Evaluation_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '440', y: '20', id: BSP_SAM_RH71_Evaluation_Kit}
