format_version: v1.0
configName: sam_rh71_ek
folderName: sst39_read_write_sam_rh71_ek
frameworkPath: C:\projects\Tools_H3\HarmonyFramework
processor: ATSAMRH71F20C
projectName: sst39_read_write_sam_rh71_ek
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMRH71_DFP\2.5.142\samrh71c\atdf\ATSAMRH71F20C.atdf
